bool request_bins
bool request_kts
---
bool response_left_bins
bool response_right_bins
bool response_kts1
bool response_kts2
ariac_msgs/AdvancedLogicalCameraImage left_bins
ariac_msgs/AdvancedLogicalCameraImage right_bins
ariac_msgs/AdvancedLogicalCameraImage kts1
ariac_msgs/AdvancedLogicalCameraImage kts2