sensors:
  bins_camera_rgb_bin1:
    type: rgb_camera
    pose:
      xyz: [-1.889745, 3.402853, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera1:
    type: basic_logical_camera
    pose:
      xyz: [-1.889745, 3.402853, 1.238667]
      rpy: [pi, pi/2, 0]
  
  bins_camera_rgb_bin2:
    type: rgb_camera
    pose:
      xyz: [-1.889745, 2.629597, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera2:
    type: basic_logical_camera
    pose:
      xyz: [-1.889745, 2.629597, 1.238667]
      rpy: [pi, pi/2, 0]

  bins_camera_rgb_bin3:
    type: rgb_camera
    pose:
      xyz: [-2.632453, 2.629597, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera3:
    type: basic_logical_camera
    pose:
      xyz: [-2.632453, 2.629597, 1.238667]
      rpy: [pi, pi/2, 0]
  
  bins_camera_rgb_bin4:
    type: rgb_camera
    pose:
      xyz: [-2.632453, 3.402853, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera4:
    type: basic_logical_camera
    pose:
      xyz: [-2.632453, 3.402853, 1.238667]
      rpy: [pi, pi/2, 0]

  bins_camera_rgb_bin5:
    type: rgb_camera
    pose:
      xyz: [-1.889745, -3.367587, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera5:
    type: basic_logical_camera
    pose:
      xyz: [-1.889745, -3.367587, 1.238667]
      rpy: [pi, pi/2, 0]

  bins_camera_rgb_bin6:
    type: rgb_camera
    pose:
      xyz: [-1.889745, -2.595141, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera6:
    type: basic_logical_camera
    pose:
      xyz: [-1.889745, -2.595141, 1.238667]
      rpy: [pi, pi/2, 0]

  bins_camera_rgb_bin7:
    type: rgb_camera
    pose:
      xyz: [-2.632453, -2.595141, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera7:
    type: basic_logical_camera
    pose:
      xyz: [-2.632453, -2.595141, 1.238667]
      rpy: [pi, pi/2, 0]

  bins_camera_rgb_bin8:
    type: rgb_camera
    pose:
      xyz: [-2.632453, -3.367587, 1.238667]
      rpy: [pi, pi/2, 0]
  bins_logical_camera8:
    type: basic_logical_camera
    pose:
      xyz: [-2.632453, -3.367587, 1.238667]
      rpy: [pi, pi/2, 0]

  kts1_rgb_camera:
    type: rgb_camera
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  kts1_logical_camera:
    type: basic_logical_camera
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_rgb_camera:
    type: rgb_camera
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]
  kts2_logical_camera:
    type: basic_logical_camera
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]
  

  
  agv1_advanced_logical_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.07, 4.8, 1.238667]
      rpy: [pi, pi/2, 0]
  agv2_advanced_logical_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.07, 1.2, 1.238667]
      rpy: [pi, pi/2, 0]
  agv3_advanced_logical_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.07, -1.2, 1.238667]
      rpy: [pi, pi/2, 0]
  agv4_advanced_logical_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.07, -4.8, 1.238667]
      rpy: [pi, pi/2, 0]

  # left_bins_camera:
  #   type: advanced_logical_camera
  #   pose:
  #     xyz: [-2.286, -2.96, 1.8]
  #     rpy: [pi, pi/2, 0]

  # kts1_camera:
  #   type: advanced_logical_camera
  #   pose:
  #     xyz: [-1.3, -5.8, 1.8]
  #     rpy: [pi, pi/2, pi/2]
  
  # kts2_camera:
  #   type: advanced_logical_camera
  #   pose:
  #     xyz: [-1.3, 5.8, 1.8]
  #     rpy: [pi, pi/2, -pi/2]